[build]
publish = "public"
command = "hugo --gc --minify"

[context.production]
environment = { HUGO_VERSION = "0.69.2", HUGO_ENV = "production" }

[context.staging]
publish = "staging"
command = "hugo --gc --minify"
environment = { HUGO_VERSION = "0.69.2", HUGO_ENV = "production" }

[context.testing]
publish = "testing"
command = "hugo --gc --buildDrafts --buildFuture --debug --enableGitInfo --logFile site.log --verbose --verboseLog"
environment = { HUGO_VERSION = "0.69.2", HUGO_ENV = "development" }